version: "3"
services:
  mongodb:
    image: "mongo:7-jammy"
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./db:/data/db
    ports:
      - 172.17.0.1:27017:27017
  minio:
    image: "elestio/minio:latest"
    restart: always
    command: server /data --address ":9000" --console-address ":9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./files:/data
  elastic:
    user: 0:0
    image: "elasticsearch:7.14.2"
    restart: always
    command: |
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;      
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    volumes:
      - ./elastic:/usr/share/elasticsearch/data
    ports:
      - 172.17.0.1:9200:9200
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - BITNAMI_DEBUG=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - http.cors.enabled=true
      - http.cors.allow-origin=https://${DOMAIN}:2702
  elasticvue:
    image: cars10/elasticvue
    restart: always
    ports:
      - 172.17.0.1:9528:8080

  account:
    image: hardcoreeng/account
    restart: always
    links:
      - mongodb
      - minio
    ports:
      - 172.17.0.1:40082:3000 #54138
    environment:
      - SERVER_PORT=3000
      - SERVER_SECRET=secret
      - MONGO_URL=mongodb://mongodb:27017
      - TRANSACTOR_URL=ws://transactor:3333
      - ENDPOINT_URL=wss://${DOMAIN}:34646
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - FRONT_URL=http://front:8080
      - INIT_WORKSPACE=demo-tracker
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=https://${DOMAIN}:54138
  front:
    image: hardcoreeng/front
    restart: always
    links:
      - mongodb
      - minio
      - elastic
      - collaborator
      - transactor
    ports:
      - 172.17.0.1:34636:8080 #443
    environment:
      - SERVER_PORT=8080
      - SERVER_SECRET=secret
      - ACCOUNTS_URL=https://${DOMAIN}:54138
      - REKONI_URL=http://${DOMAIN}:36886
      - CALENDAR_URL=http://localhost:8095
      - GMAIL_URL=http://localhost:8088
      - TELEGRAM_URL=http://localhost:8086
      - UPLOAD_URL=/files
      - TRANSACTOR_URL=wss://${DOMAIN}:34646
      - ELASTIC_URL=http://elastic:9200
      - COLLABORATOR_URL=wss://${DOMAIN}:24154
      - COLLABORATOR_API_URL=https://${DOMAIN}:24154
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - TITLE=DevPlatform
      - DEFAULT_LANGUAGE=ru
      - LAST_NAME_FIRST=true
  collaborator:
    image: hardcoreeng/collaborator
    restart: always
    links:
      - mongodb
      - minio
      - transactor
    ports:
      - 172.17.0.1:8611:3078 #24154
    environment:
      - COLLABORATOR_PORT=3078
      - SECRET=secret
      - ACCOUNTS_URL=http://account:3000
      - TRANSACTOR_URL=wss://${DOMAIN}:34646
      - UPLOAD_URL=/files
      - MONGO_URL=mongodb://mongodb:27017
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
  # tracker-front:
  #   image: hardcoreeng/tracker-front
  #   links:
  #     - mongodb
  #     - minio
  #     - elastic
  #     - transactor
  #   ports:
  #     - 8084:8080
  #   environment:
  #     - SERVER_PORT=8080
  #     - SERVER_SECRET=secret
  #     - ACCOUNTS_URL=http://localhost:3000
  #     - FRONT_URL=http://localhost:8084
  #     - UPLOAD_URL=/files
  #     - TRANSACTOR_URL=wss://${DOMAIN}:34646
  #     - ELASTIC_URL=http://elastic:9200
  #     - MINIO_ENDPOINT=minio
  #     - MINIO_ACCESS_KEY=root
  #     - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
  transactor:
    image: hardcoreeng/transactor
    restart: always
    links:
      - mongodb
      - elastic
      - minio
      - rekoni
      - account
      # - apm-server
    ports:
      - 172.17.0.1:61030:3333 #34646
    environment:
      - SERVER_PORT=3333
      - SERVER_SECRET=secret
      - SERVER_CURSOR_MAXTIMEMS=30000
      - ELASTIC_URL=http://elastic:9200
      - MONGO_URL=mongodb://mongodb:27017
      - METRICS_CONSOLE=false
      - METRICS_FILE=metrics.txt
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - REKONI_URL=http://rekoni:4004
      - FRONT_URL=https://${DOMAIN}
      # - APM_SERVER_URL=http://apm-server:8200
      - SERVER_PROVIDER=ws
      - ACCOUNTS_URL=http://account:3000
      - LAST_NAME_FIRST=true
  rekoni:
    image: hardcoreeng/rekoni-service
    restart: always
    ports:
      - 172.17.0.1:55195:4004 #36886
    deploy:
      resources:
        limits:
          memory: 500M
  # etcd:
  #   container_name: milvus-etcd
  #   image: quay.io/coreos/etcd:v3.5.0
  #   environment:
  #     - ETCD_AUTO_COMPACTION_MODE=revision
  #     - ETCD_AUTO_COMPACTION_RETENTION=1000
  #     - ETCD_QUOTA_BACKEND_BYTES=4294967296
  #     - ETCD_SNAPSHOT_COUNT=50000
  #   volumes:
  #     - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
  #   command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
  #   restart: unless-stopped
